server.port=3000
server.address=127.0.0.1

spring.datasource.url=jdbc:postgresql://localhost:5432/fitness
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false